### ISSUE TITLE
Differentiation of vector functions

### ISSUE THREAD

**Issue by bharswami** [auto-differentiation/xad#118] opened 2024-06-09 06:55 UTC
Is it possible to have a feature to compute Jacobian? Differentiating a vector function with a vector of variables. 
Or is it already available?

**Comment by raneamri** [comment] 2024-06-09 15:13
We're currently working on this feature and it should release in the near future. Note your issue is a duplicate of [Issue #37](https://github.com/auto-differentiation/xad/issues/37).

**Closed** 2024-06-09 21:39 UTC
Labels: enhancement

**Comment by bharswami** [comment] 2024-06-11 16:32
Not going to be implemented?
